// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_ktB0uBgEPdU1tfaUfxWJ3sTqgEMmvs',
    appId: '1:386908666811:web:7a85cd8b8e4be985c1229e',
    messagingSenderId: '386908666811',
    projectId: 'wingedwordsadmin',
    authDomain: 'wingedwordsadmin.firebaseapp.com',
    storageBucket: 'wingedwordsadmin.appspot.com',
    measurementId: 'G-3Y419NL8TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UsZoJKJxhKivV5mOMlVUpQo2yb9Y58c',
    appId: '1:386908666811:android:fe010b4a17b053c0c1229e',
    messagingSenderId: '386908666811',
    projectId: 'wingedwordsadmin',
    storageBucket: 'wingedwordsadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbrLCOQEhQrA7W0KSDD4HbPzlIUcUHlQ',
    appId: '1:386908666811:ios:cd83c5a5a039ac4bc1229e',
    messagingSenderId: '386908666811',
    projectId: 'wingedwordsadmin',
    storageBucket: 'wingedwordsadmin.appspot.com',
    iosBundleId: 'com.example.wingedwords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbrLCOQEhQrA7W0KSDD4HbPzlIUcUHlQ',
    appId: '1:386908666811:ios:7c046bb17e10c71fc1229e',
    messagingSenderId: '386908666811',
    projectId: 'wingedwordsadmin',
    storageBucket: 'wingedwordsadmin.appspot.com',
    iosBundleId: 'com.example.wingedwords.RunnerTests',
  );
}
